# 국민건강보험공단_건강검진정보_2021_12 분석
건강검진 결과지 제대로 읽는 법


https://health.chosun.com/site/data/html_dir/2016/11/30/2016113001291.html

In [1]:
url1="https://raw.githubusercontent.com/KimYounghwan/bigdata/master/%EA%B5%AD%EB%AF%BC%EA%B1%B4%EA%B0%95%EB%B3%B4%ED%97%98%EA%B3%B5%EB%8B%A8_%EA%B1%B4%EA%B0%95%EA%B2%80%EC%A7%84%EC%A0%95%EB%B3%B4_20211229_1.CSV"
url2="https://raw.githubusercontent.com/KimYounghwan/bigdata/master/%EA%B5%AD%EB%AF%BC%EA%B1%B4%EA%B0%95%EB%B3%B4%ED%97%98%EA%B3%B5%EB%8B%A8_%EA%B1%B4%EA%B0%95%EA%B2%80%EC%A7%84%EC%A0%95%EB%B3%B4_20211229_2.CSV"
url3="https://raw.githubusercontent.com/KimYounghwan/bigdata/master/%EA%B5%AD%EB%AF%BC%EA%B1%B4%EA%B0%95%EB%B3%B4%ED%97%98%EA%B3%B5%EB%8B%A8_%EA%B1%B4%EA%B0%95%EA%B2%80%EC%A7%84%EC%A0%95%EB%B3%B4_20211229_3.CSV"
url4="https://raw.githubusercontent.com/KimYounghwan/bigdata/master/%EA%B5%AD%EB%AF%BC%EA%B1%B4%EA%B0%95%EB%B3%B4%ED%97%98%EA%B3%B5%EB%8B%A8_%EA%B1%B4%EA%B0%95%EA%B2%80%EC%A7%84%EC%A0%95%EB%B3%B4_20211229_4.CSV"

In [62]:
import pandas as pd

검진정보1=pd.read_csv(url1)
검진정보2=pd.read_csv(url2)
검진정보3=pd.read_csv(url3)
검진정보4=pd.read_csv(url4)

In [64]:
검진정보 = 검진정보1.append(검진정보2).append(검진정보3).append(검진정보4)
#검진정보

`검진정보 복사본 생성`

In [48]:
검진정보_copy = 검진정보.copy()
검진정보_copy

,기준년도,가입자 일련번호,시도코드,성별코드,연령대 코드(5세단위),신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),...,혈청크레아티닌,(혈청지오티)AST,(혈청지오티)ALT,감마 지티피,흡연상태,음주여부,구강검진 수검여부,치아우식증유무,치석,데이터 공개일자
0,2020,1,36,1,9,165,60,72.1,1.2,1.5,...,1.1,21.0,27.0,21.0,1.0,0.0,0,NaN,NaN,2021-12-29
1,2020,2,27,2,13,150,65,81.0,0.8,0.8,...,0.5,18.0,15.0,15.0,1.0,0.0,0,NaN,NaN,2021-12-29
2,2020,3,11,2,12,155,55,70.0,0.6,0.7,...,0.7,27.0,25.0,7.0,1.0,0.0,0,NaN,NaN,2021-12-29
3,2020,4,31,1,13,160,70,90.8,1.0,1.0,...,1.2,65.0,97.0,72.0,1.0,0.0,1,0.0,0.0,2021-12-29
4,2020,5,41,2,12,155,50,75.2,1.5,1.2,...,0.7,18.0,17.0,14.0,1.0,0.0,0,NaN,NaN,2021-12-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,2020,999996,41,2,13,145,55,81.0,0.9,1.0,...,0.6,21.0,25.0,18.0,1.0,0.0,0,NaN,NaN,2021-12-29
249996,2020,999997,26,2,12,160,55,76.5,1.5,1.5,...,0.8,21.0,14.0,19.0,1.0,1.0,0,NaN,NaN,2021-12-29
249997,2020,999998,48,1,9,175,70,85.0,1.2,1.2,...,0.9,26.0,20.0,17.0,1.0,1.0,0,NaN,NaN,2021-12-29
249998,2020,999999,48,2,9,160,70,91.0,0.6,0.5,...,1.0,25.0,29.0,13.0,1.0,0.0,0,NaN,NaN,2021-12-29
249999,2020,1000000,28,1,11,160,55,76.1,2.0,2.0,...,0.9,17.0,13.0,24.0,2.0,0.0,0,NaN,NaN,2021-12-29

`시도 코드 추가`

In [49]:
dic1 = {11 : '서울특별시',
26 : '부산광역시',
27 : '대구광역시',
28 : '인천광역시',
29 : '광주광역시',
30 : '대전광역시',
31 : '울산광역시',
36 : '세종특별자치시',
41 : '경기도',
42 : '강원도',
43 : '충청북도',
44 : '충청남도',
45 : '전라북도',
46 : '전라남도',
47 : '경상북도' ,
48 : '경상남도',
49 : '제주특별자치도'}

검진정보_copy['시도명'] = 검진정보_copy['시도코드'].apply(lambda x : dic1[x])
검진정보_copy.drop('시도코드', axis=1, inplace=True)
검진정보_copy.head(1)
#검진정보_copy

,기준년도,가입자 일련번호,성별코드,연령대 코드(5세단위),신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),청력(좌),...,(혈청지오티)AST,(혈청지오티)ALT,감마 지티피,흡연상태,음주여부,구강검진 수검여부,치아우식증유무,치석,데이터 공개일자,시도명
0,2020,1,1,9,165,60,72.1,1.2,1.5,1.0,...,21.0,27.0,21.0,1.0,0.0,0,NaN,NaN,2021-12-29,세종특별자치시

`연령대 코드 추가`  
`2014년 이후 코드 사용`

In [50]:
age_list = ['0~4세','5~9세','10~14세',
                '15~19세','20~24세','25~29세',
                '30~34세','35~39세','40~44세',
                '45~49세','50~54세','55~59세',
                '60~64세','65~69세','70~74세',
               '75~79세','80~84세','85세 이상']
검진정보_copy['연령대'] = 검진정보_copy['연령대 코드(5세단위)'].apply(lambda x:age_list[x-1])
검진정보_copy.drop('연령대 코드(5세단위)', axis=1, inplace=True)
검진정보_copy.head(1)
#검진정보_copy

,기준년도,가입자 일련번호,성별코드,신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),청력(좌),청력(우),...,(혈청지오티)ALT,감마 지티피,흡연상태,음주여부,구강검진 수검여부,치아우식증유무,치석,데이터 공개일자,시도명,연령대
0,2020,1,1,165,60,72.1,1.2,1.5,1.0,1.0,...,27.0,21.0,1.0,0.0,0,NaN,NaN,2021-12-29,세종특별자치시,40~44세

`성별 칼럼 추가`

In [51]:
검진정보_copy['성별'] = 검진정보_copy['성별코드'].apply(lambda x:'남자' if x==1 else '여자')
검진정보_copy.drop('성별코드', axis=1, inplace=True)
검진정보_copy.head(1)

,기준년도,가입자 일련번호,신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),청력(좌),청력(우),수축기 혈압,...,감마 지티피,흡연상태,음주여부,구강검진 수검여부,치아우식증유무,치석,데이터 공개일자,시도명,연령대,성별
0,2020,1,165,60,72.1,1.2,1.5,1.0,1.0,127.0,...,21.0,1.0,0.0,0,NaN,NaN,2021-12-29,세종특별자치시,40~44세,남자

`사용하지 않는 칼럼 제거`

In [52]:
검진정보_copy.drop(['기준년도','가입자 일련번호','데이터 공개일자'], axis=1, inplace=True)
검진정보_copy.head(1)

,신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),청력(좌),청력(우),수축기 혈압,이완기 혈압,식전혈당(공복혈당),...,(혈청지오티)ALT,감마 지티피,흡연상태,음주여부,구강검진 수검여부,치아우식증유무,치석,시도명,연령대,성별
0,165,60,72.1,1.2,1.5,1.0,1.0,127.0,79.0,90.0,...,27.0,21.0,1.0,0.0,0,NaN,NaN,세종특별자치시,40~44세,남자

In [53]:
검진정보_copy2

,신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),청력(좌),청력(우),수축기 혈압,이완기 혈압,식전혈당(공복혈당),...,요단백,혈청크레아티닌,(혈청지오티)AST,(혈청지오티)ALT,감마 지티피,흡연상태,음주여부,구강검진 수검여부,치아우식증유무,치석
0,165,60,72.1,1.2,1.5,1.0,1.0,127.0,79.0,90.0,...,1.0,1.1,21.0,27.0,21.0,1.0,0.0,0,NaN,NaN
1,150,65,81.0,0.8,0.8,1.0,1.0,110.0,73.0,87.0,...,1.0,0.5,18.0,15.0,15.0,1.0,0.0,0,NaN,NaN
2,155,55,70.0,0.6,0.7,1.0,1.0,123.0,80.0,102.0,...,1.0,0.7,27.0,25.0,7.0,1.0,0.0,0,NaN,NaN
3,160,70,90.8,1.0,1.0,1.0,2.0,134.0,84.0,146.0,...,1.0,1.2,65.0,97.0,72.0,1.0,0.0,1,0.0,0.0
4,155,50,75.2,1.5,1.2,1.0,1.0,144.0,89.0,110.0,...,1.0,0.7,18.0,17.0,14.0,1.0,0.0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,145,55,81.0,0.9,1.0,1.0,1.0,132.0,78.0,124.0,...,1.0,0.6,21.0,25.0,18.0,1.0,0.0,0,NaN,NaN
249996,160,55,76.5,1.5,1.5,1.0,1.0,100.0,64.0,98.0,...,1.0,0.8,21.0,14.0,19.0,1.0,1.0,0,NaN,NaN
249997,175,70,85.0,1.2,1.2,1.0,1.0,110.0,64.0,83.0,...,1.0,0.9,26.0,20.0,17.0,1.0,1.0,0,NaN,NaN
249998,160,70,91.0,0.6,0.5,1.0,1.0,137.0,82.0,111.0,...,1.0,1.0,25.0,29.0,13.0,1.0,0.0,0,NaN,NaN
249999,160,55,76.1,2.0,2.0,1.0,1.0,133.0,74.0,121.0,...,1.0,0.9,17.0,13.0,24.0,2.0,0.0,0,NaN,NaN

`시도명, 연령대, 성별 칼럼 맨 앞으로 가져오기`

In [57]:
검진정보_copy1 = 검진정보_copy[['시도명', '연령대', '성별']]
검진정보_copy2 = 검진정보_copy.loc[:,'신장(5Cm단위)':'치석']
검진정보_merge = pd.concat([검진정보_copy1, 검진정보_copy2], axis=1)
검진정보_merge.head(1)

# merge한 데이터 검진정보_copy에 저장
검진정보_copy = 검진정보_merge.copy()
#검진정보_copy

`20200407 - 점심시간 이후 모임`

In [66]:
검진정보_copy = 검진정보.copy()
검진정보_copy

dic1 = {11 : '서울특별시',
26 : '부산광역시',
27 : '대구광역시',
28 : '인천광역시',
29 : '광주광역시',
30 : '대전광역시',
31 : '울산광역시',
36 : '세종특별자치시',
41 : '경기도',
42 : '강원도',
43 : '충청북도',
44 : '충청남도',
45 : '전라북도',
46 : '전라남도',
47 : '경상북도' ,
48 : '경상남도',
49 : '제주특별자치도'}

age_list = ['0~4세','5~9세','10~14세',
                '15~19세','20~24세','25~29세',
                '30~34세','35~39세','40~44세',
                '45~49세','50~54세','55~59세',
                '60~64세','65~69세','70~74세',
               '75~79세','80~84세','85세 이상']

# 코드 변환 후 새로운 칼럼 추가, 기존 코드 칼럼 삭제
검진정보_copy['시도명'] = 검진정보_copy['시도코드'].apply(lambda x : dic1[x])
검진정보_copy.drop('시도코드', axis=1, inplace=True)
검진정보_copy['연령대'] = 검진정보_copy['연령대 코드(5세단위)'].apply(lambda x:age_list[x-1])
검진정보_copy.drop('연령대 코드(5세단위)', axis=1, inplace=True)
검진정보_copy['성별'] = 검진정보_copy['성별코드'].apply(lambda x:'남자' if x==1 else '여자')
검진정보_copy.drop('성별코드', axis=1, inplace=True)

# 필요없는 칼럼 삭제
검진정보_copy.drop(['기준년도','가입자 일련번호','데이터 공개일자'], axis=1, inplace=True)

#시도명, 연령대, 성별 칼럼 맨 앞으로 가져오기
검진정보_copy1 = 검진정보_copy[['시도명', '연령대', '성별']]
검진정보_copy2 = 검진정보_copy.loc[:,'신장(5Cm단위)':'치석']
검진정보_merge = pd.concat([검진정보_copy1, 검진정보_copy2], axis=1)


# merge한 데이터 검진정보_copy에 저장
검진정보_copy = 검진정보_merge.copy()
#검진정보_copy